server:
  port: 4455

spring:
  datasource:
    url: jdbc:mysql://${AWS_RDS_MYSQL_URL}:3306/productsdb
    username: ${AWS_RDS_MYSQL_USERNAME}
    password: ${AWS_RDS_MYSQL_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
