spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 4455


aws:
  region: ap-south-1

rds:
  db:
    endpoint: employees-database.c1vd6amykmfy.ap-south-1.rds.amazonaws.com
    username: db_iam_user
